name: verby_mobile
description: Verby Mobile

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # >>> Verby Mobile Packages >>>
  verby_mobile_design_tokens:
    git:
      url: https://github.com/verby-korea/verby-mobile-design-tokens.git
      ref: develop
  # <<< Verby Mobile Packages <<<

  # >>> External Packages >>>
  either_dart: 0.2.0
  equatable: 2.0.3
  http: 0.13.5
  # <<< External Packages <<<

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
